### ISSUE TITLE
Rename repo to conventions

### ISSUE THREAD

**Issue by danielgomezrico** [nullindustries/code_style#8]
Maybe code style is not the right name for it?

**Comment by jfelipe** [comment]
One year later but I think the same, what about Guidelines, blueprints?

**Comment by orendon** [comment]
`craftsman-rule-book`? 🙈

**Comment by edwaraco** [comment]
`craftsman-hand-book` :speak_no_evil:

**Comment by orendon** [comment]
Renamed by voz Populi
